# Generated by Django 2.1 on 2021-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210301_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='estoque_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
