# Generated by Django 2.1 on 2021-03-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_produtos_estoque_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='estoque_min',
            new_name='estoque_minimo',
        ),
    ]
