# Generated by Django 2.1 on 2021-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210302_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='numero_nf',
            field=models.CharField(max_length=255),
        ),
    ]
