# Generated by Django 2.1 on 2021-03-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210308_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
