# Generated by Django 2.1 on 2021-03-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210308_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.IntegerField(blank=True),
        ),
    ]
