# Generated by Django 2.1 on 2021-03-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210309_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacoes',
            options={'ordering': ['created_at']},
        ),
    ]
