# Generated by Django 2.1 on 2021-03-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210309_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacoes',
            options={'ordering': ['-created_at']},
        ),
    ]
