# Generated by Django 2.1 on 2021-03-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210309_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='movimentacoes',
            name='clientes',
        ),
        migrations.AddField(
            model_name='clientes',
            name='movimentacoes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Movimentacoes'),
            preserve_default=False,
        ),
    ]
