# Generated by Django 2.1 on 2021-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_movimentacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoes',
            name='produto',
            field=models.ForeignKey(default=1, on_delete='cascade', to='website.produtos'),
            preserve_default=False,
        ),
    ]
